export const SHOWSIDEDRAWER = "SHOWSIDEDRAWER"
export const SETUSERDATA = "SETUSERDATA"

export const SETUSERDATASTART = "SETUSERDATASTART"
export const SETUSERDATASUCCESS = "SETUSERDATASUCCESS"

export const OUTPUTLIST = "OUTPUTLIST"
export const FILTERVALUE = "FILTERVALUE"

export const EDITVALUE = "EDITVALUE"
export const TOGGLE_EDITMODAL = "TOGGLE_EDITMODAL"
export const FILTERVALUEPH = "FILTERVALUEPH"